USE [CMPT291_Project];
GO

DROP TABLE Rented
DROP TABLE Employee
DROP TABLE Customer
DROP TABLE Car
DROP TABLE CarType
DROP TABLE Branch

CREATE TABLE Customer(
    CID INT IDENTITY(1, 1) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    DateOfBirth DATE NOT NULL,
    DriversLicense VARCHAR(15) NOT NULL UNIQUE,
    PhoneNumber VARCHAR(15) NOT NULL UNIQUE,
	CONSTRAINT CK_Customer_DriversLicense CHECK (LEN(DriversLicense) >= 7 AND LEN(DriversLicense) <= 15)
);

CREATE TABLE CarType(
	Type VARCHAR(50) PRIMARY KEY,
	Daily MONEY NOT NULL,
	Weekly MONEY NOT NULL,
	Monthly MONEY NOT NULL
);

CREATE TABLE Branch(
	 BID INT IDENTITY(1, 1) PRIMARY KEY,
	 BranchName VARCHAR(50) NOT NULL,
	 Street VARCHAR(50) NOT NULL,
	 City VARCHAR(50) NOT NULL,
	 Province VARCHAR(50) NOT NULL,
	 Country VARCHAR(50) NOT NULL,
	 CONSTRAINT UQ_Branch UNIQUE (BranchName, Street, City, Province, Country)
);

CREATE TABLE Car(
	VIN VARCHAR(17) PRIMARY KEY, --We will assume all VINs are 17 characters long
	Brand VARCHAR(50) NOT NULL,
	Make VARCHAR(50) NOT NULL,
	Availability BIT NOT NULL,
	LicensePlate VARCHAR(6) NOT NULL UNIQUE, -- We will assume they are Canadian license plate so it can have 6 max characters
	Type VARCHAR(50) NOT NULL,
	BID int NOT NULL,
	FOREIGN KEY (Type) REFERENCES CarType(Type) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (BID) REFERENCES Branch(BID),
	CONSTRAINT CK_Car_VIN CHECK (LEN(VIN) = 17),
	CONSTRAINT CK_Car_LicensePlate CHECK (LEN(LicensePlate) <= 6)
);

CREATE TABLE Employee(
	EID INT IDENTITY (100, 1) PRIMARY KEY,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Salary MONEY NOT NULL,
	BID INT NOT NULL,
	FOREIGN KEY (BID) REFERENCES Branch(BID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Rented(
	RID INT IDENTITY(1, 1) PRIMARY KEY,
	PickUpDate DATE NOT NULL,
	PickUpBID INT NOT NULL,
	DropOffDate DATE NOT NULL,
	DropOffBID INT NOT NULL,
	VIN VARCHAR(17) NOT NULL,
	CID INT NOT NULL,
	EID INT NOT NULL,
	TotalPrice MONEY NOT NULL,
	FOREIGN KEY (PickUpBID) REFERENCES Branch(BID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (DropOffBID) REFERENCES Branch(BID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (VIN) REFERENCES Car(VIN) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CID) REFERENCES Customer(CID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (EID) REFERENCES Employee(EID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT CK_Rented_DropOffDate CHECK (DropOffDate >= PickUpDate)
);


